name = "sassymcp-oauth"
main = "src/index.js"
compatibility_date = "2026-04-01"
workers_dev = false
 
[[routes]]
pattern = "mcp-oauth.sassyconsultingllc.com"
custom_domain = true
 
[[kv_namespaces]]
binding = "OAUTH_KV"
id = "b1de2b1d40f8421ca46db2117e21824f"
 
[vars]
UPSTREAM_URL = "https://mcp.sassyconsultingllc.com/mcp"
 